POST http://localhost:8080/events
Content-Type: application/json

{
    "name":"test Event test",
	"description":"a test event description   are testie ",
	"location":"dezful city",
	"dateTime":"2025-01-01T15:30:40.000Z" 
}