DELETE  http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wZWwuY29tIiwiZXhwIjoxNzA0OTEyMDIxLCJ1c2VySWQiOjJ9.FtQq6SB0to_t4Xe3YNF4J-NHY_S1G6mR0I7eYWDBmgE
